version: '3'
services:
  angular-app:
    build:
      context: ./hello-world-app
      dockerfile: Dockerfile
    ports:
      - 80:80

  flask-app:
    build:
      context: ./flask-backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
