version: '3'
services:
  angular-app:
    build:
      context: ./hello-world-app
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - app-network

  flask-app:
    build:
      context: ./flask-backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - app-network

networks:
  app-network:
